version: '3'
services:
  web:
    build: .
    ports:
      - "443:443"
    environment:
      - ANTHROPIC_API_KEY=your_anthropic_api_key
      - OPENAI_API_KEY=your_openai_api_key
      - GEMINI_API_KEY=your_gemini_api_key